export const installed_blueprints = [
  //@BlueprintInsertion
{ name: 'Messaging8018', human_name: 'Messaging', access_route: 'Messaging8018', icon: 'comments'},
{ name: 'BlankScreen28017', human_name: 'Blank Screen 2', access_route: 'BlankScreen28017'},
{ name: 'BlankScreen28016', human_name: 'Blank Screen 2', access_route: 'BlankScreen28016'},
{ name: 'BlankScreen18015', human_name: 'Blank Screen 1', access_route: 'BlankScreen18015'},
{ name: 'BlankScreen28014', human_name: 'Blank Screen 2', access_route: 'BlankScreen28014'},
{ name: 'BlankScreen18013', human_name: 'Blank Screen 1', access_route: 'BlankScreen18013'},
{ name: 'BlankScreen28012', human_name: 'Blank Screen 2', access_route: 'BlankScreen28012'},
{ name: 'BlankScreen18010', human_name: 'Blank Screen 1', access_route: 'BlankScreen18010'},
{ name: 'BlankScreen48004', human_name: 'Blank Screen 4', access_route: 'BlankScreen48004'},
{ name: 'CalendarView8003', human_name: 'Calendar View', access_route: 'CalendarView8003', icon: 'calendar'},
{ name: 'EmailAuth8002', human_name: 'Email Auth', access_route: 'EmailAuth8002', icon: 'envelope-o'},
{ name: 'Messaging8001', human_name: 'Messaging', access_route: 'Messaging8001', icon: 'comments'},
{ name: 'Messaging8000', human_name: 'Messaging', access_route: 'Messaging8000', icon: 'comments'},
{ name: 'EmailAuth7999', human_name: 'Email Auth', access_route: 'EmailAuth7999', icon: 'envelope-o'},
{ name: 'CalendarView7998', human_name: 'Calendar View', access_route: 'CalendarView7998', icon: 'calendar'},
{ name: 'BlankScreen47997', human_name: 'Blank Screen 4', access_route: 'BlankScreen47997'},
{ name: 'BlankScreen97996', human_name: 'Blank Screen 9', access_route: 'BlankScreen97996'},
{ name: 'BlankScreen107995', human_name: 'Blank Screen 10', access_route: 'BlankScreen107995'},
{ name: 'BlankScreen107989', human_name: 'Blank Screen 10', access_route: 'BlankScreen107989'},
{ name: 'BlankScreen97988', human_name: 'Blank Screen 9', access_route: 'BlankScreen97988'},
{ name: 'BlankScreen47982', human_name: 'Blank Screen 4', access_route: 'BlankScreen47982'},
{ name: 'CalendarView7981', human_name: 'Calendar View', access_route: 'CalendarView7981', icon: 'calendar'},
{ name: 'EmailAuth7980', human_name: 'Email Auth', access_route: 'EmailAuth7980', icon: 'envelope-o'},
{ name: 'Messaging7979', human_name: 'Messaging', access_route: 'Messaging7979', icon: 'comments'},
{ name: 'Messaging7970', human_name: 'Messaging', access_route: 'Messaging7970', icon: 'comments'},
{ name: 'EmailAuth7969', human_name: 'Email Auth', access_route: 'EmailAuth7969', icon: 'envelope-o'},
{ name: 'CalendarView7968', human_name: 'Calendar View', access_route: 'CalendarView7968', icon: 'calendar'},
{ name: 'Messenger', human_name: 'Messenger', access_route: 'Messenger', icon: 'comments'},
{ name: 'Calendar', human_name: 'Calendar', access_route: 'Calendar', icon: 'calendar'},
{ name: 'EmailAuth', human_name: 'EmailAuth', access_route: 'EmailAuth', icon: 'envelope-o'},

  // you can add more installed blueprints here
  // access route is the route nate given to navigator
];
