# Generated by Django 2.2.14 on 2020-07-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='hgjjkjkkk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='oojuhhj',
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
    ]
