# Generated by Django 2.2.14 on 2020-07-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200706_0647"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="hgjjkjkkk",),
        migrations.RemoveField(model_name="customtext", name="oojuhhj",),
    ]
